### ISSUE TITLE
Run the prr's Pydro example in Python 3

### ISSUE THREAD

**Issue by giumas** [hydroffice/hyo2_openbst#1]

**Comment by zxcvbnmike15** [comment]
Functionality has been implemented in commit eac9a8a7131e0ce6715837f056dbe6c75858d0b1
on the glen code branch

**Comment by giumas** [comment]
I pushed the 'glen_code' branch on the main repository (https://github.com/hydroffice/hyo2_openbst). No need to continue the development in your fork.
