### ISSUE TITLE
Bug - Windows does not release control of netcdf files on rebuild of project

### ISSUE THREAD

**Issue by msmith-ccom** [hydroffice/hyo2_openbst#23]
When re-creating a project (using force_new flag is true)

![pycharm64_lmsQsa1lTo](https://user-images.githubusercontent.com/9027655/73129921-73f41900-3fbc-11ea-9550-1867effbec92.png)

Windows does not tend to release control of one of the project .nc files (typically project_info.nc).
![notepad_1TYtKiJsQc](https://user-images.githubusercontent.com/9027655/73129927-9d14a980-3fbc-11ea-9947-d30ecdc3fcdb.png)

This causes a permission error when attempting to delete the file during project creation.

**Comment by giumas** [comment]
The issue is caused by the combination of two factors: 1) you re-use "default" as project name, 2) the tests are executed in parallel. We discussed it during my past visit. The solution is to simply use different project names: https://github.com/hydroffice/hyo2_openbst/pull/30

**Comment by msmith-ccom** [comment]
Correct. I will merg your changes
