### ISSUE TITLE
Codacy Invalid Syntax Issue

### ISSUE THREAD

**Issue by msmith-ccom** [hydroffice/hyo2_openbst#25]
For each run of Codacy, I get an invalid syntax issue (see below)
![gitkraken_WtY4MNShdJ](https://user-images.githubusercontent.com/9027655/73495502-a9b24c80-4384-11ea-9ac6-9e83c715b8d9.png)

This is not invalid syntax. 

The impression from this [link](https://blog.codacy.com/which-python-static-analysis-tools-should-i-use/) indicates that codacy uses either pylint or pyflakes, or other to run the static analysis. Not sure how that is set up.
@giumas  it would be nice if I could be added to the codacy organization.

Either way, the closest matching issue I found was a Flake8 issue seen [here]
(https://gitlab.com/pycqa/flake8/issues/284) and I think the issue on our end is similar with codacy not recognizing typing maybe. Though this would be inconsistent as typing is used throughout the code base

This is a weird bug and I would like to not be failing codacy every time so it would be nice to get this fixed. Otherwise I will continue to ignore it.

**Comment by giumas** [comment]
@zxcvbnmike15: your email was already in the Codacy team. I have deleted it and re-added. Does it work now?

**Comment by giumas** [comment]
I have upgraded the files to ignore:
![chrome_6k3x2VIr2y](https://user-images.githubusercontent.com/2849257/73596949-a4d9ce00-4527-11ea-9277-07068089209d.png)

Thus, Codacy should only run on the content under the "hyo2" folder.

**Comment by giumas** [comment]
The issue is actually coming from Prospector:
![chrome_NRM3okf4Hc](https://user-images.githubusercontent.com/2849257/73597171-95f41b00-4529-11ea-96d7-e374cc918d74.png)

It is a known issue: https://github.com/codacy/codacy-meta/issues/186

I am just disabling Prospector until the issue is solved by Codacy.

**Comment by msmith-ccom** [comment]
Thanks Giuseppe. This hits all the right marks. Next time you're in town you will have to give me the run down on Codacy.
