### ISSUE TITLE
Using type() instead of isinstance() for a typecheck.

### ISSUE THREAD

**Issue by giumas** [hydroffice/hyo2_openbst#31]
#### Currently on:
+ **Commit**:  76ddfec45e410a115fa07b6eea12a233e3c41c88
+ **File**:    [hyo2/openbst/lib/processing/process.py](https://github.com/hydroffice/hyo2_openbst/blob/76ddfec45e410a115fa07b6eea12a233e3c41c88/hyo2/openbst/lib/processing/process.py)
+ **LineNum**: [115](https://github.com/hydroffice/hyo2_openbst/blob/76ddfec45e410a115fa07b6eea12a233e3c41c88/hyo2/openbst/lib/processing/process.py#L115)

**Comment by msmith-ccom** [comment]
Fixed in PR #37
