### ISSUE TITLE
Unused variable 'process_written'

### ISSUE THREAD

**Issue by giumas** [hydroffice/hyo2_openbst#32]
#### Currently on:
+ **Commit**:  76ddfec45e410a115fa07b6eea12a233e3c41c88
+ **File**:    [hyo2/openbst/lib/processing/process.py](https://github.com/hydroffice/hyo2_openbst/blob/76ddfec45e410a115fa07b6eea12a233e3c41c88/hyo2/openbst/lib/processing/process.py)
+ **LineNum**: [120](https://github.com/hydroffice/hyo2_openbst/blob/76ddfec45e410a115fa07b6eea12a233e3c41c88/hyo2/openbst/lib/processing/process.py#L120)

**Comment by msmith-ccom** [comment]
Fixed in pull request #37
